"""empty message

Revision ID: 1b5584dcb7e1
Revises: 3b29272fb52
Create Date: 2014-12-29 19:14:01.876000

"""

# revision identifiers, used by Alembic.
revision = '1b5584dcb7e1'
down_revision = '3b29272fb52'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    ### end Alembic commands ###
