"""empty message

Revision ID: 1be9e74c2d9e
Revises: 26a497682310
Create Date: 2015-05-16 20:09:34.112000

"""

# revision identifiers, used by Alembic.
revision = '1be9e74c2d9e'
down_revision = '26a497682310'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_enrollments')
    ### end Alembic commands ###
