"""empty message

Revision ID: 1fdb7fe551b
Revises: 3fb87aaf164d
Create Date: 2015-10-31 22:08:55.123115

"""

# revision identifiers, used by Alembic.
revision = '1fdb7fe551b'
down_revision = '3fb87aaf164d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    ### end Alembic commands ###
