"""empty message

Revision ID: 23a3c0623a8
Revises: 1fdb7fe551b
Create Date: 2015-11-18 19:28:49.018981

"""

# revision identifiers, used by Alembic.
revision = '23a3c0623a8'
down_revision = '1fdb7fe551b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('symbols_concept_id_fkey', 'symbols', type_='foreignkey')
    op.drop_constraint('symbols_language_id_fkey', 'symbols', type_='foreignkey')
    op.create_foreign_key(None, 'symbols', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'symbols', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('words_concept_id_fkey', 'words', type_='foreignkey')
    op.drop_constraint('words_language_id_fkey', 'words', type_='foreignkey')
    op.create_foreign_key(None, 'words', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'words', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.drop_constraint(None, 'words', type_='foreignkey')
    op.create_foreign_key('words_language_id_fkey', 'words', 'languages', ['language_id'], ['id'])
    op.create_foreign_key('words_concept_id_fkey', 'words', 'concepts', ['concept_id'], ['id'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_constraint(None, 'symbols', type_='foreignkey')
    op.drop_constraint(None, 'symbols', type_='foreignkey')
    op.create_foreign_key('symbols_language_id_fkey', 'symbols', 'languages', ['language_id'], ['id'])
    op.create_foreign_key('symbols_concept_id_fkey', 'symbols', 'concepts', ['concept_id'], ['id'])
    ### end Alembic commands ###
