"""empty message

Revision ID: 23e909d72d18
Revises: 4aba438f5b1a
Create Date: 2014-12-30 18:59:08.346000

"""

# revision identifiers, used by Alembic.
revision = '23e909d72d18'
down_revision = '4aba438f5b1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
