"""empty message

Revision ID: 2429d3daa7d
Revises: 3930c7ad602
Create Date: 2015-11-18 20:27:17.331518

"""

# revision identifiers, used by Alembic.
revision = '2429d3daa7d'
down_revision = '3930c7ad602'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('concept_list_concepts_concept_list_id_fkey', 'concept_list_concepts', type_='foreignkey')
    op.drop_constraint('concept_list_concepts_concept_id_fkey', 'concept_list_concepts', type_='foreignkey')
    op.create_foreign_key(None, 'concept_list_concepts', 'concept_lists', ['concept_list_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'concept_list_concepts', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'concept_list_concepts', type_='foreignkey')
    op.drop_constraint(None, 'concept_list_concepts', type_='foreignkey')
    op.create_foreign_key('concept_list_concepts_concept_id_fkey', 'concept_list_concepts', 'concepts', ['concept_id'], ['id'])
    op.create_foreign_key('concept_list_concepts_concept_list_id_fkey', 'concept_list_concepts', 'concept_lists', ['concept_list_id'], ['id'])
    ### end Alembic commands ###
