"""empty message

Revision ID: 25ebcfcdb805
Revises: 3f04b4b50a1a
Create Date: 2015-05-16 19:50:46.993000

"""

# revision identifiers, used by Alembic.
revision = '25ebcfcdb805'
down_revision = '3f04b4b50a1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
