"""empty message

Revision ID: 26a497682310
Revises: 25ebcfcdb805
Create Date: 2015-05-16 20:00:13.935000

"""

# revision identifiers, used by Alembic.
revision = '26a497682310'
down_revision = '25ebcfcdb805'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
