"""empty message

Revision ID: 302a038a7515
Revises: 3dc3658f1582
Create Date: 2015-01-11 03:09:23.450000

"""

# revision identifiers, used by Alembic.
revision = '302a038a7515'
down_revision = '3dc3658f1582'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_answers', sa.Column('createdDate', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_answers', 'createdDate')
    ### end Alembic commands ###
