"""empty message

Revision ID: 312ac7cc296e
Revises: 302a038a7515
Create Date: 2015-01-12 08:19:01.396000

"""

# revision identifiers, used by Alembic.
revision = '312ac7cc296e'
down_revision = '302a038a7515'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_lists', sa.Column('foreign_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'word_lists_test_id_fkey', 'word_lists', type_='foreignkey')
    op.create_foreign_key(None, 'word_lists', 'languages', ['foreign_id'], ['id'])
    op.drop_column('word_lists', u'test_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_lists', sa.Column(u'test_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'word_lists', type_='foreignkey')
    op.create_foreign_key(u'word_lists_test_id_fkey', u'word_lists', u'languages', [u'test_id'], [u'id'])
    op.drop_column('word_lists', 'foreign_id')
    ### end Alembic commands ###
