"""empty message

Revision ID: 33183529c11f
Revises: 49aec0d64887
Create Date: 2015-01-16 03:15:35.997000

"""

# revision identifiers, used by Alembic.
revision = '33183529c11f'
down_revision = '49aec0d64887'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concept_list_concepts',
    sa.Column('concept_list_id', sa.Integer(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['concept_list_id'], ['concept_lists.id'], )
    )
    op.drop_table(u'word_list_concepts')
    op.drop_table(u'word_lists')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'word_lists',
    sa.Column(u'id', sa.INTEGER(), server_default=sa.text(u"nextval('word_lists_id_seq'::regclass)"), nullable=False),
    sa.Column(u'native_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column(u'foreign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'foreign_id'], [u'languages.id'], name=u'word_lists_foreign_id_fkey'),
    sa.ForeignKeyConstraint([u'native_id'], [u'languages.id'], name=u'word_lists_native_id_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'word_lists_pkey')
    )
    op.create_table(u'word_list_concepts',
    sa.Column(u'word_list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'concept_id'], [u'concepts.id'], name=u'word_list_concepts_concept_id_fkey'),
    sa.ForeignKeyConstraint([u'word_list_id'], [u'word_lists.id'], name=u'word_list_concepts_word_list_id_fkey')
    )
    op.drop_table('concept_list_concepts')
    op.drop_table('concept_lists')
    ### end Alembic commands ###
