"""empty message

Revision ID: 348b2c672a27
Revises: 3d9a5b029f89
Create Date: 2015-01-13 17:45:14.356000

"""

# revision identifiers, used by Alembic.
revision = '348b2c672a27'
down_revision = '3d9a5b029f89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password', sa.UnicodeText(), nullable=False),
    sa.Column('givenName', sa.UnicodeText(), nullable=True),
    sa.Column('lastName', sa.UnicodeText(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###
