"""empty message

Revision ID: 3930c7ad602
Revises: 23a3c0623a8
Create Date: 2015-11-18 20:25:06.955659

"""

# revision identifiers, used by Alembic.
revision = '3930c7ad602'
down_revision = '23a3c0623a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answers_mastery_id_fkey', 'answers', type_='foreignkey')
    op.create_foreign_key(None, 'answers', 'masteries', ['mastery_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('language_enrollments_user_id_fkey', 'language_enrollments', type_='foreignkey')
    op.drop_constraint('language_enrollments_language_id_fkey', 'language_enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'language_enrollments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'language_enrollments', 'languages', ['language_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('learned_symbols_symbol_id_fkey', 'learned_symbols', type_='foreignkey')
    op.drop_constraint('learned_symbols_user_id_fkey', 'learned_symbols', type_='foreignkey')
    op.create_foreign_key(None, 'learned_symbols', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'learned_symbols', 'symbols', ['symbol_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('learned_words_user_id_fkey', 'learned_words', type_='foreignkey')
    op.drop_constraint('learned_words_word_id_fkey', 'learned_words', type_='foreignkey')
    op.create_foreign_key(None, 'learned_words', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'learned_words', 'words', ['word_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('masteries_word_id_fkey', 'masteries', type_='foreignkey')
    op.drop_constraint('masteries_symbol_id_fkey', 'masteries', type_='foreignkey')
    op.create_foreign_key(None, 'masteries', 'words', ['word_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'masteries', 'symbols', ['symbol_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masteries', type_='foreignkey')
    op.drop_constraint(None, 'masteries', type_='foreignkey')
    op.create_foreign_key('masteries_symbol_id_fkey', 'masteries', 'symbols', ['symbol_id'], ['id'])
    op.create_foreign_key('masteries_word_id_fkey', 'masteries', 'words', ['word_id'], ['id'])
    op.drop_constraint(None, 'learned_words', type_='foreignkey')
    op.drop_constraint(None, 'learned_words', type_='foreignkey')
    op.create_foreign_key('learned_words_word_id_fkey', 'learned_words', 'words', ['word_id'], ['id'])
    op.create_foreign_key('learned_words_user_id_fkey', 'learned_words', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'learned_symbols', type_='foreignkey')
    op.drop_constraint(None, 'learned_symbols', type_='foreignkey')
    op.create_foreign_key('learned_symbols_user_id_fkey', 'learned_symbols', 'users', ['user_id'], ['id'])
    op.create_foreign_key('learned_symbols_symbol_id_fkey', 'learned_symbols', 'symbols', ['symbol_id'], ['id'])
    op.drop_constraint(None, 'language_enrollments', type_='foreignkey')
    op.drop_constraint(None, 'language_enrollments', type_='foreignkey')
    op.create_foreign_key('language_enrollments_language_id_fkey', 'language_enrollments', 'languages', ['language_id'], ['id'])
    op.create_foreign_key('language_enrollments_user_id_fkey', 'language_enrollments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.create_foreign_key('answers_mastery_id_fkey', 'answers', 'masteries', ['mastery_id'], ['id'])
    ### end Alembic commands ###
