"""empty message

Revision ID: 398e36caec53
Revises: 351a0acad5cf
Create Date: 2015-01-14 05:28:17.738000

"""

# revision identifiers, used by Alembic.
revision = '398e36caec53'
down_revision = '351a0acad5cf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_masteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('mastery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mastery_id'], ['word_masteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'answers')
    op.drop_table(u'masteries')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'masteries',
    sa.Column(u'id', sa.INTEGER(), server_default=sa.text(u"nextval('masteries_id_seq'::regclass)"), nullable=False),
    sa.Column(u'user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column(u'word_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'user_id'], [u'users.id'], name=u'masteries_user_id_fkey'),
    sa.ForeignKeyConstraint([u'word_id'], [u'words.id'], name=u'masteries_word_id_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'masteries_pkey')
    )
    op.create_table(u'answers',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column(u'createdDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column(u'mastery_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint([u'mastery_id'], [u'masteries.id'], name=u'answers_mastery_id_fkey'),
    sa.PrimaryKeyConstraint(u'id', name=u'answers_pkey')
    )
    op.drop_table('word_answers')
    op.drop_table('word_masteries')
    ### end Alembic commands ###
