"""empty message

Revision ID: 3b29272fb52
Revises: None
Create Date: 2014-12-29 19:13:04.086000

"""

# revision identifiers, used by Alembic.
revision = '3b29272fb52'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
