"""empty message

Revision ID: 3b535fde11a4
Revises: 2a19b49a24ea
Create Date: 2015-05-16 19:40:51.767000

"""

# revision identifiers, used by Alembic.
revision = '3b535fde11a4'
down_revision = '2a19b49a24ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
