"""empty message

Revision ID: 3d57cf80d680
Revises: 58cc8ca0faa2
Create Date: 2015-01-30 22:04:41.420000

"""

# revision identifiers, used by Alembic.
revision = '3d57cf80d680'
down_revision = '58cc8ca0faa2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staleness_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('first', sa.Boolean(), nullable=True),
    sa.Column('next_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_id'], ['staleness_periods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'masteries', sa.Column('staleness_period_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'masteries', 'staleness_periods', ['staleness_period_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masteries', type_='foreignkey')
    op.drop_column(u'masteries', 'staleness_period_id')
    op.drop_table('staleness_periods')
    ### end Alembic commands ###
