"""empty message

Revision ID: 3d9a5b029f89
Revises: 312ac7cc296e
Create Date: 2015-01-13 17:36:07.664000

"""

# revision identifiers, used by Alembic.
revision = '3d9a5b029f89'
down_revision = '312ac7cc296e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
