"""empty message

Revision ID: 3dc3658f1582
Revises: 451134745663
Create Date: 2015-01-06 16:16:54.241000

"""

# revision identifiers, used by Alembic.
revision = '3dc3658f1582'
down_revision = '451134745663'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_masteries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.Column('word_mastery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['word_mastery_id'], ['word_masteries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_answers')
    op.drop_table('word_masteries')
    ### end Alembic commands ###
