"""empty message

Revision ID: 3f04b4b50a1a
Revises: 3b535fde11a4
Create Date: 2015-05-16 19:44:48.997000

"""

# revision identifiers, used by Alembic.
revision = '3f04b4b50a1a'
down_revision = '3b535fde11a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
