"""empty message

Revision ID: 41eb180f4673
Revises: 3d57cf80d680
Create Date: 2015-05-15 02:18:26.791000

"""

# revision identifiers, used by Alembic.
revision = '41eb180f4673'
down_revision = '3d57cf80d680'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('native_language_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'languages', ['native_language_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'native_language_id')
    ### end Alembic commands ###
