"""empty message

Revision ID: 45a9ecfe5b70
Revises: 41eb180f4673
Create Date: 2015-05-16 00:24:49.025000

"""

# revision identifiers, used by Alembic.
revision = '45a9ecfe5b70'
down_revision = '41eb180f4673'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
