"""empty message

Revision ID: 45a9ecfe5b70
Revises: 41eb180f4673
Create Date: 2015-05-16 00:24:49.025000

"""

# revision identifiers, used by Alembic.
revision = '45a9ecfe5b70'
down_revision = '41eb180f4673'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_enrollments',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_enrollments')
    ### end Alembic commands ###
