"""empty message

Revision ID: 494341a83ccc
Revises: 33183529c11f
Create Date: 2015-01-16 06:14:47.502000

"""

# revision identifiers, used by Alembic.
revision = '494341a83ccc'
down_revision = '33183529c11f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept_lists', sa.Column('isWords', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept_lists', 'isWords')
    ### end Alembic commands ###
