"""empty message

Revision ID: 49aec0d64887
Revises: 252f79c87c2d
Create Date: 2015-01-14 05:41:57.284000

"""

# revision identifiers, used by Alembic.
revision = '49aec0d64887'
down_revision = '252f79c87c2d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
