"""empty message

Revision ID: 4f66c600764a
Revises: 494341a83ccc
Create Date: 2015-01-16 19:04:03.588000

"""

# revision identifiers, used by Alembic.
revision = '4f66c600764a'
down_revision = '494341a83ccc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.UnicodeText(), nullable=True),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'masteries', sa.Column('symbol_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'masteries', 'symbols', ['symbol_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'masteries', type_='foreignkey')
    op.drop_column(u'masteries', 'symbol_id')
    op.drop_table('symbols')
    ### end Alembic commands ###
